1. Challenge 1:

- Answer: b
- Explanation: It's a because you can update the value of the variable (foo) since it was declared using let. So the value is updated inside the function.

2. Challenge 2:

- Answer: c
- Explanation: The value of a was re-declared inside the function so the console.log inside the function will print that value, and the console.log outside the function will print the original value.

3. Challenge 3:

- Answer: c
- Explanation: functions can work in asynchronous way

4. Challenge 4:

- Answer: c
- Explanation: the value of num in a was updated inderectly

5. Bonus - Challenge 5:

- Answer: c
- Explanation: I am not 100% certain but i think that it's this one because obj.age is updated
